"""Added component model changes

Revision ID: 93b96898adfa
Revises: 
Create Date: 2024-04-25 14:18:57.460001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93b96898adfa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Component', schema=None) as batch_op:
        batch_op.alter_column('projectId',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Component', schema=None) as batch_op:
        batch_op.alter_column('projectId',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
