version: '3.8'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    image: pg-db
    ports:
      - "5432:5432"

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    image: app-image
    ports:
      - "8000:8000"



