# Use the official PostgreSQL image as the base image
FROM postgres:latest

# Set the environment variables for the PostgreSQL database
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD pass
ENV POSTGRES_DB 24040_db


# Expose the default PostgreSQL port
EXPOSE 5432
